### ISSUE TITLE
Update of Histogram not working after changing with the handles.

### ISSUE THREAD

**Issue by l00mi** [zazuko/zack-search#20]

**Comment by bergos** [comment]
Should be fixed with [this commit](https://github.com/zazuko/zack-search/commit/66f15a73f66b7d2b5ae8c3f6793ec11acfa40796).

**Comment by l00mi** [comment]
hmm, i still experience the same effect, lets look at this together once?

**Comment by ktk** [comment]
Same here, can't really get it to work anymore

**Comment by bergos** [comment]
Sorry, not fixed, but now I'm sure it runs into the [update code](https://github.com/zazuko/zack-search/blob/develop/lib/histogram.js#L82). I think it's a d3 problem. @l00mi can you have a look at it?

**Comment by larsvers** [comment]
We might want to look down this rabbit hole together. The (short) problem flow is as follows:

1) histogram formulates query within brush, sending off the brushed dates
2) query gets send (I guess triggered by the handle `onchange`?)
3) response returns with different dates and respective bucket data.

All years are rounded to 1st of Jan (the brush usually returns second-precise dates), which is fine. 
The date differences between queried dates and response dates are usually small when the brush appears before 1948. 

However, any brush with a `toHandle` date beyond 1948 ends up either at 1948 (if the `fromHandle` date is before 1948) or with a `toHandle` date of 2000 or empty dates. 

Some examples:

     Query: [Wed Feb 05 1862 21:54:00 GMT+0100 (CET), Tue May 06 1969 02:42:15 GMT+0200 (CEST)]
     Response: {start: Thu Jan 01 1863 01:00:00 GMT+0100 (CET), end: Thu Jan 01 1948 01:00:00 GMT+0100 (CET)}

     Query: [Fri Jul 03 1840 01:17:34 GMT+0200 (CEST), Thu Aug 01 1940 17:42:55 GMT+0200 (CEST)]
     Response: {start: Sun Jan 01 1837 01:00:00 GMT+0100 (CET), end: Sun Jan 01 1933 01:00:00 GMT+0100 (CET)}

     Query: [Sun Oct 04 1959 15:42:28 GMT+0200 (CEST), Wed Dec 26 1979 07:18:55 GMT+0100 (CET)]
     Response: {start: "", end: ""}

     Query: [Sun May 03 1959 17:51:43 GMT+0200 (CEST), Sat Jan 01 2000 01:00:00 GMT+0100 (CET)]
     Response: {start: Sat Jan 01 2000 01:00:00 GMT+0100 (CET), end: Sat Jan 01 2000 01:00:00 GMT+0100 (CET)}

     Query: [Tue May 15 1934 13:29:13 GMT+0200 (CEST), Sun Jun 06 1943 15:10:33 GMT+0200 (CEST)]
     Response: {start: Wed Jan 01 1941 01:00:00 GMT+0100 (CET), end: Thu Jan 01 1942 01:00:00 GMT+0100 (CET)}
